### ISSUE TITLE
Implement a first version of the ETL for Kids First Data Portal

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-etl#5]
- [ ] How to get data, warehouse it and make it available for a pipeline
- [ ] Provision an infrastructure on AWS. Make it reproducible, identify frameworks.
- [ ] Transform data into ES
- [ ] Identify/build data model we conform to
- [ ] Identify data loading strategy - Incremental? Batch? Streaming? Hybrid (lambda architecture? kappa architecture?)

**Comment by grant-guo** [comment]
progress on Jan-30-2018
finish pipeline and processors implementations. what is left is data models and how to load the data the first time
